# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vsX1xmnCvLP55JL_7JcBUAT1IXS2cFQO
"""

# --------------- Imports ---------------
# I import os in case I need file path or environment utilities later.
import os

# I import json because the ticker mapping file is stored in JSON format.
import json

# I import numpy and pandas for data handling and computation in later steps.
import numpy as np
import pandas as pd

# I use Google Colab's file upload widget to allow interactive uploads.
from google.colab import files

# I import matplotlib for plots produced later in the notebook.
import matplotlib.pyplot as plt


# ==================================================
# 1. Data Upload
# ==================================================
# In this first step, I clearly tell the user which files must be uploaded.
# I want them to upload everything in one go to avoid  errors later.

print("Please upload the following files in one go:")

# I list the SEC zip files needed for the three fiscal-year snapshots I analyze.
print(" - 2017q4.zip, 2018q4.zip, 2019q4.zip (SEC FSD)")

# I list the JSON mapping file that I use to convert CIKs to tickers.
print(" - company_tickers.json (CIK -> ticker mapping)")

# I list the macro sentiment file used for the 2017–2019 window.
print(" - UMCSENT CSV (Univ. of Michigan sentiment, 2017–2019)")

uploaded = files.upload()


# -------------------- Identify SEC zip files --------------------
# I define the three SEC periods I need.
periods = ["2017q4", "2018q4", "2019q4"]

# I build a dictionary mapping each period to the correct uploaded zip filename.
# This dictionary is later used when unzipping and processing each SEC archive.
SEC_ZIPS = {p: find_file(p) for p in periods}

# I print the resolved filenames so I can verify that the matching worked.
print("SEC zip files:", SEC_ZIPS)


# -------------------- Identify ticker JSON --------------------
# I search for the JSON that contains the word "ticker".
TICKER_JSON = find_file("ticker")

# I print the matched JSON filename for confirmation.
print("Ticker JSON:", TICKER_JSON)


# -------------------- Identify UMich sentiment CSV --------------------
# I try two possible keyword patterns to handle slight naming differences.
try:
    # First, I look for a file that contains "umcsent".
    UMICH_CSV = find_file("umcsent")
except ValueError:
    # If that fails, I fall back to searching for a more generic "sent".
    UMICH_CSV = find_file("sent")

# I print the final sentiment file name so I can confirm it was found.
print("UMich CSV:", UMICH_CSV)


# FULL Process AFTER Data UPLOAD
#   1) Unzip SEC archives,
#   2) Build SEC features per period,
#   3) Build firm-year panel (2017–2019),
#   4) Map CIK → ticker,
#   5) Download prices & define target,
#   6) Merge UMich sentiment,
#   7) Build modelling dataset & features,
#   8) Winsorise ratios & train Random Forest,
#   9) Model diagnostics & feature importance


# --------------- 1. Unzip SEC archives ---------------
# First, I extract each zipped SEC dataset into a period-specific folder, allowing me to keep raw files organized and avoids mixing quarters.

for p in periods:
    # I grab the relevant .zip file name for this SEC period.
    zip_name = SEC_ZIPS[p]

    # I create a consistent folder name where this period's files will live.
    folder   = f"fsd_{p}"

    # I print progress so it's clear which archive I'm handling.
    print(f"Unzipping {zip_name} -> {folder}")

    # I create the folder if it doesn't exist. Using quotes protects against spaces and parentheses in file names.
    !mkdir -p "{folder}"

    # I unzip the archive into the target folder (overwriting if needed).
    !unzip -o "{zip_name}" -d "{folder}"


# --------------- 2. Build SEC features per period ---------------
# The goal of this section is to transform raw SEC data into a clean firm-year feature dataset that I can later merge across periods.

def build_features_for_period(period_code):
    """
    Build cleaned + transformed SEC features for one period (e.g. '2018q4').

    -I read raw SEC submission + numeric files.
    - I keep only 10-K style filings (annual, comparable across firms).
    - I select a specific set of meaningful accounting tags.
    - I drop raw tags with too much missingness (>25%).
    - I impute missing values using a structured approach:
        asset-size bucket × year median
        then year median
        then global median
    - I log-transform highly right-skewed levels.
    - I construct standard financial ratios.
    - Again, I impute missing ratio values using the same structured logic.
    """

    # I point to the folder containing this period's unzipped SEC files.
    folder = f"fsd_{period_code}"

    # --- Read raw SEC datasets ---
    # 'sub.txt' contains filing-level identifiers and metadata.
    sub = pd.read_csv(f"{folder}/sub.txt", sep=None, engine="python", dtype=str)

    # 'num.txt' contains reported numerical values for each tag.
    # I allow skipping bad lines because SEC raw files can contain irregular rows.
    num = pd.read_csv(
        f"{folder}/num.txt",
        sep=None,
        engine="python",
        dtype=str,
        on_bad_lines="skip"
    )

    # I standardize column naming to reduce awkward column references later.
    sub.columns = sub.columns.str.strip()
    num.columns = num.columns.str.strip().str.lower()

    # I create a helper that locates required columns robustly,even if there are small formatting differences in the raw files.
    def find_col(df, target):
        for c in df.columns:
            if c.strip().lower() == target:
                return c
        raise ValueError(f"Could not find '{target}' in {folder}/sub.txt")

    # I identify key columns needed to connect filings to firm-year financials.
    form_col = find_col(sub, "form")
    adsh_col = find_col(sub, "adsh")
    cik_col  = find_col(sub, "cik")
    fy_col   = find_col(sub, "fy")

    # --- Filter to comparable annual filings ---
    # I keep only 10-K and close variants to ensure I'm using annual financial reports.
    sub_10k = sub[sub[form_col].str.upper().isin(["10-K", "10-K405", "10-K/A"])].copy()

    # I keep only the minimal identifiers I need for merging.
    sub_10k = sub_10k[[adsh_col, cik_col, fy_col]]
    sub_10k.columns = ["adsh", "cik", "fy"]

    # --- Choose accounting tags ---
    # I define a curated list of core financial statement items.
    raw_tags = [
        "Revenues",
        "InterestExpense",
        "PaymentsToAcquirePropertyPlantAndEquipment",
        "Liabilities",
        "PropertyPlantAndEquipmentNet",
        "OperatingIncomeLoss",
        "NetCashProvidedByUsedInOperatingActivities",
        "LiabilitiesCurrent",
        "AssetsCurrent",
        "CashAndCashEquivalentsAtCarryingValue",
        "StockholdersEquity",
        "NetIncomeLoss",
        "LiabilitiesAndStockholdersEquity",
        "Assets",
    ]

    # I filter numeric data to:
    #  - only the tags I care about,
    #  - only USD values,
    #  - only annual-style horizons (qtrs = 4) or stocks (qtrs = 0).
    num_filt = num[
        num["tag"].isin(raw_tags)
        & (num["uom"] == "USD")
        & (num["qtrs"].astype(float).isin([0, 4]))
    ].copy()

    # I convert the value column to numeric, coercing any odd entries into NaN.
    num_filt["value"] = pd.to_numeric(num_filt["value"], errors="coerce")

    # I merge numeric values with 10-K metadata to connect each number to a firm-year.
    merged = num_filt.merge(sub_10k, on="adsh", how="inner")

    # --- Pivot to wide firm-year format ---
    # I convert long tag-level data into one row per (cik, fy),
    # which is what a model-ready feature table needs.
    wide = merged.pivot_table(
        index=["cik", "fy"],
        columns="tag",
        values="value",
        aggfunc="last"
    ).reset_index()
    wide.columns.name = None

    # I define firm-year identifiers.
    id_cols  = ["cik", "fy"]

    # I keep only tags that actually survived the pivot.
    raw_cols = [c for c in raw_tags if c in wide.columns]

    # I build the initial raw feature dataframe.
    df_feat = wide[id_cols + raw_cols].copy()

    # I ensure fiscal year is numeric to support numeric comparisons and grouping.
    df_feat["fy"] = pd.to_numeric(df_feat["fy"], errors="coerce")

    # ---- Drop raw features with too much missingness ----
    # I compute the percent missing per raw tag.
    missing_frac = df_feat[raw_cols].isna().mean()

    # I keep only tags with <= 25% missing values.
    raw_cols = missing_frac[missing_frac <= 0.25].index.tolist()

    # I subset to the retained raw columns.
    df_feat = df_feat[id_cols + raw_cols]

    # ---- Size-bucket × year imputation for raw levels ----
    # The idea here is that firms of similar size in the same year should
    # have more comparable accounting magnitudes than the overall sample.

    if "Assets" in df_feat.columns:
        # I define asset quartiles to create size buckets.
        df_feat["size_bucket"] = pd.qcut(
            df_feat["Assets"], q=4, labels=False, duplicates="drop"
        )
    else:
        # If Assets is missing entirely, I can't construct size buckets.
        df_feat["size_bucket"] = np.nan

    for col in raw_cols:
        # First, I fill missing values using the median within (size_bucket, year).
        med_sz_yr = df_feat.groupby(["size_bucket", "fy"])[col].transform("median")
        df_feat[col] = df_feat[col].fillna(med_sz_yr)

        # Second, I fall back to the year-specific median.
        med_yr = df_feat.groupby("fy")[col].transform("median")
        df_feat[col] = df_feat[col].fillna(med_yr)

        # Third, I use the overall median of the sample.
        df_feat[col] = df_feat[col].fillna(df_feat[col].median())

    # I drop the temporary size bucket now that imputation is complete.
    df_feat.drop(columns=["size_bucket"], inplace=True)

    # ---- Log1p transform for strongly right-skewed levels ----
    # I check skewness to identify variables where log scaling is useful.
    skewness = df_feat[raw_cols].skew()

    # I mark variables that are strongly right-skewed.
    right_skewed = [c for c in raw_cols if skewness[c] > 1]

    for col in right_skewed:
        # I apply log1p so zero values don't break the transformation.
        # I also clip below 0 defensively.
        df_feat[f"log_{col}"] = np.log1p(df_feat[col].clip(lower=0))

    # ---- For visual aid: histograms of pre vs post-transformation ----
    # I drop missing values so the histograms reflect actual observed distributions. I also only plot if the log version was created.

    for col in right_skewed:
        log_col = f"log_{col}"
        if log_col not in df_feat.columns:
            continue

        # Raw distribution
        plt.figure(figsize=(6, 4))
        plt.hist(df_feat[col].dropna(), bins=30)
        plt.title(f"{period_code}: Raw {col}")
        plt.xlabel(col)
        plt.ylabel("Count")
        plt.tight_layout()
        plt.show()

        # Log-transformed distribution
        plt.figure(figsize=(6, 4))
        plt.hist(df_feat[log_col].dropna(), bins=30)
        plt.title(f"{period_code}: Log-transformed {col}")
        plt.xlabel(log_col)
        plt.ylabel("Count")
        plt.tight_layout()
        plt.show()

    # ---- Construct ratios ----
    # Ratios help normalize levels across firm size, making comparisons more meaningful for a classifier.

    def safe_div(num, den):
        # I divide and then convert infinite results into missing.
        out = num / den
        return out.replace([np.inf, -np.inf], np.nan)

    # Leverage: measure of balance sheet risk.
    if "Liabilities" in df_feat.columns and "Assets" in df_feat.columns:
        df_feat["leverage"] = safe_div(df_feat["Liabilities"], df_feat["Assets"])

    # Equity ratio: alternative capital structure measure.
    if "StockholdersEquity" in df_feat.columns and "Assets" in df_feat.columns:
        df_feat["equity_ratio"] = safe_div(df_feat["StockholdersEquity"], df_feat["Assets"])

    # Current ratio: short-term liquidity.
    if "AssetsCurrent" in df_feat.columns and "LiabilitiesCurrent" in df_feat.columns:
        df_feat["current_ratio"] = safe_div(df_feat["AssetsCurrent"], df_feat["LiabilitiesCurrent"])

    # Cash ratio: most conservative liquidity measure.
    if "CashAndCashEquivalentsAtCarryingValue" in df_feat.columns:
        # I choose a sensible denominator depending on availability.
        base = df_feat.get("LiabilitiesCurrent", df_feat.get("Liabilities"))
        if base is not None:
            df_feat["cash_ratio"] = safe_div(
                df_feat["CashAndCashEquivalentsAtCarryingValue"], base
            )

    # ROA: profitability relative to asset base.
    if "NetIncomeLoss" in df_feat.columns and "Assets" in df_feat.columns:
        df_feat["roa"] = safe_div(df_feat["NetIncomeLoss"], df_feat["Assets"])

    # Profit margin: profitability relative to revenues.
    if "NetIncomeLoss" in df_feat.columns and "Revenues" in df_feat.columns:
        df_feat["profit_margin"] = safe_div(df_feat["NetIncomeLoss"], df_feat["Revenues"])

    # Operating margin: operating income relative to revenues.
    if "OperatingIncomeLoss" in df_feat.columns and "Revenues" in df_feat.columns:
        df_feat["operating_margin"] = safe_div(df_feat["OperatingIncomeLoss"], df_feat["Revenues"])

    # Operating cash flow intensity.
    if "NetCashProvidedByUsedInOperatingActivities" in df_feat.columns and "Assets" in df_feat.columns:
        df_feat["ocf_to_assets"] = safe_div(
            df_feat["NetCashProvidedByUsedInOperatingActivities"], df_feat["Assets"]
        )

    # Capital intensity.
    if "PropertyPlantAndEquipmentNet" in df_feat.columns and "Assets" in df_feat.columns:
        df_feat["ppe_to_assets"] = safe_div(
            df_feat["PropertyPlantAndEquipmentNet"], df_feat["Assets"]
        )

    # Capex intensity.
    if "PaymentsToAcquirePropertyPlantAndEquipment" in df_feat.columns and "Assets" in df_feat.columns:
        df_feat["capex_to_assets"] = safe_div(
            df_feat["PaymentsToAcquirePropertyPlantAndEquipment"], df_feat["Assets"]
        )

    # Interest coverage: ability to meet financing costs.
    if "OperatingIncomeLoss" in df_feat.columns and "InterestExpense" in df_feat.columns:
        df_feat["interest_coverage"] = safe_div(
            df_feat["OperatingIncomeLoss"],
            df_feat["InterestExpense"].replace(0, np.nan)
        )

    # ---- Size-bucket × year imputation for ratios ----
    # I apply the same imputation logic to ratios to preserve sample size.

    ratio_cols = [
        c for c in df_feat.columns
        if c not in id_cols + raw_cols and not c.startswith("log_")
    ]

    # I ensure any infinite ratio outcomes are treated as missing before imputation.
    df_feat[ratio_cols] = df_feat[ratio_cols].replace([np.inf, -np.inf], np.nan)

    # I rebuild size buckets if possible.
    if "Assets" in df_feat.columns:
        df_feat["size_bucket"] = pd.qcut(
            df_feat["Assets"], q=4, labels=False, duplicates="drop"
        )
    else:
        df_feat["size_bucket"] = np.nan

    for col in ratio_cols:
        # First pass: size_bucket × year medians.
        med_sz_yr = df_feat.groupby(["size_bucket", "fy"])[col].transform("median")
        df_feat[col] = df_feat[col].fillna(med_sz_yr)

        # Second pass: year medians.
        med_yr = df_feat.groupby("fy")[col].transform("median")
        df_feat[col] = df_feat[col].fillna(med_yr)

        # Third pass: global median.
        df_feat[col] = df_feat[col].fillna(df_feat[col].median())

    # I remove temporary helper column.
    df_feat.drop(columns=["size_bucket"], inplace=True, errors="ignore")

    # I return a clean firm-year feature dataset for this period.
    return df_feat


# --------------- 3. Build firm-year panel (2017–2019) ---------------
# Here I loop over each period, build features, and concatenate them into a single dataset that covers all years I care about.

all_feats = []

for p in periods:
    # I track progress so I can diagnose issues by period if needed.
    print(f"Processing {p} ...")

    # I build the cleaned feature set for this SEC archive.
    all_feats.append(build_features_for_period(p))

# I stack all period-level feature datasets into one dataframe.
df_all = pd.concat(all_feats, ignore_index=True)

# I restrict to the fiscal years required for my study window.
df_panel = df_all[df_all["fy"].between(2017, 2019)].copy()

# I print the panel size to confirm the filter behaved as expected.
print("Panel rows:", len(df_panel))


# --------------- 4. Map CIK → ticker ---------------
# SEC data uses CIKs, but price data requires tickers. So this step builds a robust crosswalk.

# I load the official ticker mapping file.
with open(TICKER_JSON) as f:
    tickers_json = json.load(f)

# I convert the JSON structure into a dataframe.
tickers_df = pd.DataFrame.from_dict(tickers_json, orient="index")

# I locate the CIK column dynamically (in case its exact name differs).
cik_col_json = [c for c in tickers_df.columns if "cik" in c.lower()][0]

# I standardize CIK to numeric integer format for merging.
tickers_df["cik_int"] = tickers_df[cik_col_json].astype(int)

# I ensure I keep only one ticker per CIK in case duplicates exist.
tickers_df_unique = tickers_df.drop_duplicates("cik_int")

# I build a clean CIK → ticker lookup series.
cik_to_ticker = tickers_df_unique.set_index("cik_int")["ticker"]

# I locate the CIK column in my panel dynamically.
cik_col_panel = [c for c in df_panel.columns if "cik" in c.lower()][0]

# I convert that to a numeric key to match the JSON mapping.
df_panel["cik_int"] = df_panel[cik_col_panel].astype(int)

# I assign tickers to my panel using the crosswalk.
df_panel["ticker"] = df_panel["cik_int"].map(cik_to_ticker)

# I drop any rows where the ticker mapping failed.
df_panel = df_panel[df_panel["ticker"].notna()].copy()

# I drop redundant CIK columns to avoid confusion downstream.
drop_cik_cols = [c for c in df_panel.columns if "cik" in c.lower() and c != "cik_int"]
df_panel = df_panel.drop(columns=drop_cik_cols)

# I report how many unique tickers remain in my modelling pool.
print("Unique tickers:", df_panel["ticker"].nunique())


# --------------- 5. Download prices & define target ---------------
# My goal here is to build a price panel aligned with fiscal years and define whether the next-year price is higher than the current-year price.

# I install yfinance inside the environment if needed.
!pip install yfinance -q
import yfinance as yf

# I extract a sorted list of the unique tickers in my panel.
tickers_list = sorted(df_panel["ticker"].unique().tolist())

# I define my price download window.
# I need enough data to cover FY 2017–2019 and their next-year outcomes.
start, end = "2017-01-01", "2021-01-15"

# I use batching to reduce request size and avoid API instability.
batch_size = 100

# I store extracted year-end prices here.
rows = []

# I loop in batches of tickers.
for i in range(0, len(tickers_list), batch_size):

    # I select the current batch.
    batch = tickers_list[i:i+batch_size]

    # I log progress to know where errors might occur.
    print(f"Downloading prices for tickers {i}–{i+len(batch)-1}...")

    # I download price data for this batch and let yfinance group results by ticker.
    data = yf.download(
        batch, start=start, end=end,
        auto_adjust=True, group_by="ticker",
        progress=False
    )

    # I iterate through each ticker to compute year-end prices.
    for t in batch:
        try:
            # If batch size is 1, yfinance returns a direct dataframe.
            # Otherwise it returns a multi-ticker dictionary-like object.
            df_t = data if len(batch) == 1 else data[t]

            # If no data exists for this ticker, I skip it.
            if df_t.empty:
                continue

            # I make a copy to avoid modifying the original object.
            df_t = df_t.copy()

            # I extract year from the date index.
            df_t["year"] = df_t.index.year

            # I keep the last closing price of each year as my year-end price proxy.
            year_end = (
                df_t.groupby("year")["Close"]
                    .last()
                    .reset_index()
                    .rename(columns={"Close": "price_year_end"})
            )

            # I restrict to relevant years used in FY and FY+1 comparison.
            year_end = year_end[year_end["year"].between(2017, 2020)]

            # For each fiscal year, I collect the year-end price and the next year's price.
            for fy in [2017, 2018, 2019]:

                # I extract the current FY year-end price if available.
                p_fy   = year_end.loc[year_end["year"] == fy,   "price_year_end"]

                # I extract the next-year price if available.
                p_next = year_end.loc[year_end["year"] == fy+1, "price_year_end"]

                # I convert the one-element series to scalar values.
                p_fy   = p_fy.iloc[0]   if len(p_fy)   else np.nan
                p_next = p_next.iloc[0] if len(p_next) else np.nan

                # I store the ticker-year price pair.
                rows.append({
                    "ticker": t, "fy": fy,
                    "price_fy": p_fy, "price_next": p_next
                })

        except Exception:
            # If anything fails for this ticker, I fill NaNs for all FYs.
            for fy in [2017, 2018, 2019]:
                rows.append({
                    "ticker": t, "fy": fy,
                    "price_fy": np.nan, "price_next": np.nan
                })

# I convert the extracted price rows into a dataframe.
prices_panel = pd.DataFrame(rows)

# I merge prices onto my fundamentals panel using ticker and fiscal year.
df_panel = df_panel.merge(prices_panel, on=["ticker", "fy"], how="left")

# I drop rows where I cannot observe both FY price and FY+1 price.
# This ensures the target is not implicitly defined using missing values.
df_panel = df_panel.dropna(subset=["price_fy", "price_next"])

# I define my binary outcome: 1 if price increases from FY to FY+1, 0 otherwise.
df_panel["price_up_next"] = (df_panel["price_next"] > df_panel["price_fy"]).astype(int)


# --------------- 6. Merge UMich sentiment ---------------
# This step adds a macro-level sentiment measure that varies by year, which allows me to test whether broader economic mood contributes to prediction.

# I read the University of Michigan sentiment file.
umich = pd.read_csv(UMICH_CSV)

# I locate the relevant columns dynamically for robustness.
date_col = [c for c in umich.columns if "date" in c.lower()][0]
sent_col = [c for c in umich.columns if "umcsent" in c.lower()][0]

# I convert the date column to a datetime format.
umich["date"] = pd.to_datetime(umich[date_col])

# I extract year so I can aggregate sentiment annually.
umich["year"] = umich["date"].dt.year

# I compute average sentiment for each calendar year.
econ_by_year = (
    umich.groupby("year")[sent_col]
         .mean()
         .reset_index()
         .rename(columns={sent_col: "UMCSENT_mean"})
)

# I standardize the annual sentiment series to create a z-score.
mean_all = econ_by_year["UMCSENT_mean"].mean()
std_all  = econ_by_year["UMCSENT_mean"].std()
econ_by_year["econ_sentiment"] = (econ_by_year["UMCSENT_mean"] - mean_all) / std_all

# I restrict to years overlapping my fundamentals panel.
econ_panel = econ_by_year[econ_by_year["year"].between(2017, 2019)].copy()

# I rename 'year' to 'fy' so the merge key matches the panel.
econ_panel.rename(columns={"year": "fy"}, inplace=True)

# I merge sentiment into the panel by fiscal year.
df_panel = df_panel.merge(econ_panel, on="fy", how="left")


# --------------- 7. Build modelling dataset & features ---------------
# Here I define my target, make explicit what I should not treat as features, and build my final feature list.

# I keep a working copy for modelling.
df_model   = df_panel.copy()

# I define the target column for classification.
target_col = "price_up_next"

# I list columns that should not be used to predict the outcome. These include the target itself, price variables, and identifiers.
drop_as_features = [
    target_col, "price_fy", "price_next", "cik_int", "fy"
]

# These are intended transformed level variables.
log_level_vars = [
    "log_Assets", "log_Revenues", "log_Liabilities",
    "log_AssetsCurrent", "log_LiabilitiesCurrent",
    "log_StockholdersEquity", "log_CashAndCashEquivalentsAtCarryingValue",
    "log_PropertyPlantAndEquipmentNet", "log_InterestExpense",
    "log_NetIncomeLoss", "log_OperatingIncomeLoss",
    "log_NetCashProvidedByUsedInOperatingActivities",
    "log_PaymentsToAcquirePropertyPlantAndEquipment",
    "log_LiabilitiesAndStockholdersEquity",
]

# These are the interpretable financial ratios.
ratio_vars = [
    "leverage", "equity_ratio", "current_ratio", "cash_ratio",
    "roa", "profit_margin", "operating_margin",
    "ocf_to_assets", "ppe_to_assets", "capex_to_assets",
    "interest_coverage",
]

# This is my macro feature and I explicitly require it.
other_vars = ["econ_sentiment"]

# I build a candidate list but only keep variables present in the dataframe.
feature_candidates = [
    c for c in (log_level_vars + ratio_vars + other_vars)
    if c in df_model.columns and c not in drop_as_features
]

# I remove features that are entirely missing or constant.
feature_cols = [
    c for c in feature_candidates
    if df_model[c].notna().any() and df_model[c].nunique() > 1
]

# I enforce that econ_sentiment must remain in the final model.
assert "econ_sentiment" in feature_cols, "econ_sentiment dropped by mistake!"
print("Number of features:", len(feature_cols))


# --------------- 8. Winsorise ratios & train Random Forest ---------------
# Before training, I cap extreme ratio values to reduce outlier-driven noise.

ratio_cols_for_winsor = [
    "roa", "profit_margin", "leverage", "current_ratio", "cash_ratio",
    "ppe_to_assets", "ocf_to_assets", "capex_to_assets", "interest_coverage",
]

for col in ratio_cols_for_winsor:
    if col in df_model.columns:
        # I compute the 1st and 95th percentiles.
        q_low, q_high = df_model[col].quantile([0.01, 0.95])

        # I clip values outside this range.
        df_model[col] = df_model[col].clip(lower=q_low, upper=q_high)

# I import train/test split utilities and the Random Forest model.
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

# I create a copy before imputation so my original panel remains intact.
df_model_imp = df_model.copy()

# I fill remaining missing values in features using median imputation. This ensures the Random Forest receives a complete matrix.
for col in feature_cols:
    med = df_model_imp[col].median()
    df_model_imp[col] = df_model_imp[col].fillna(med)

# I remove any rows with missing targets.
df_model_clean = df_model_imp.dropna(subset=[target_col])

# I build the feature matrix X and outcome vector y.
X = df_model_clean[feature_cols].values
y = df_model_clean[target_col].values

# I split into training and held-out test sets. Stratifying ensures the class balance is similar in both sets.
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

# I define the Random Forest hyperparameters. 500 trees improves stability.
rf = RandomForestClassifier(
    n_estimators=500,
    max_depth=None,
    random_state=42
)

# I fit the model on the training set only.
rf.fit(X_train, y_train)

# I evaluate accuracy on the held-out test set.
rf_acc = rf.score(X_test, y_test)
print("Random Forest accuracy on test set:", round(rf_acc, 3))

# --- Majority class baseline ---
# This baseline helps me gauge whether the model adds value over a naive rule.

# I identify the majority class in the training set.
vals, counts = np.unique(y_train, return_counts=True)
maj_class = vals[np.argmax(counts)]

# I predict the majority class for every test observation.
baseline_acc = (np.full_like(y_test, maj_class) == y_test).mean()
print("Baseline (majority class) accuracy on test:", round(baseline_acc, 3))


# --------------- 9. Model diagnostics & feature importance ---------------
# Here I generate:
"""
 - classification report
 - confusion matrix
 - feature importance ranking
"""

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay,
    auc
)
import matplotlib.pyplot as plt

# I generate predicted classes on the test set.
y_pred  = rf.predict(X_test)


# I print precision, recall, f1-score for each class.
print("\nClassification report:\n", classification_report(y_test, y_pred))

# I compute the confusion matrix to view error types directly.
cm = confusion_matrix(y_test, y_pred)

# I plot the matrix for a visual summary of correct vs incorrect predictions.
ConfusionMatrixDisplay(cm).plot(cmap="Blues")
plt.title("Random Forest – Confusion Matrix")
plt.show()


# --- Feature Importance ---
# Random Forests provide impurity-based importance, which I use to rank which variables contribute most to prediction.

importances = rf.feature_importances_

# I convert importance weights into a labeled series for readability.
feat_imp = pd.Series(importances, index=feature_cols).sort_values()

# I plot a horizontal bar chart so the ranking is easy to interpret.
plt.figure(figsize=(8, 5))
plt.barh(feat_imp.index, feat_imp.values)
plt.xlabel("Feature importance")
plt.title("Random Forest Feature Importances")
plt.tight_layout()
plt.show()